[package]
name = "devtui"
version = "0.1.0"
edition = "2021"

[lib]
name = "devtui"
path = "src/lib.rs"

[[bin]]
name = "devtui"
path = "src/bin/editor.rs"

[[bin]]
name = "devtui-engine"
path = "src/bin/engine.rs"

[dependencies]
ratatui = "0.29"
crossterm = "0.28"
pulldown-cmark = "0.12"
tui-term = "0.2.0"
vt100 = "0.15"
portable-pty = "0.9"
toml = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
gh-emoji = "1.0"
tiny_http = "0.12"
rusqlite = { version = "0.31", features = ["bundled"] }
log = "0.4"
simplelog = "0.12"
ureq = { version = "3", features = ["json"] }
